# Generated by Django 4.1.3 on 2022-11-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('discription', models.TextField(verbose_name='discription')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('categary', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=2, verbose_name='state')),
                ('product_image', models.ImageField(upload_to='producting', verbose_name='product_image')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
